# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Samantha Quiñones
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

description: Samantha Quiñones' Blog
author:
  name: Samantha Quiñones
  github: squinones
  twitter: ieatkillerbees
  linkedin: samanthaquinones
  bio: PHP & Python hacker, lead engineer @POLITICO
  email_md5: 24368af16c4b0946ece77da839b7b53a

base_url: http://www.samanthaquinones.com/
rss_path: feed.xml
categories_path: categories.html
calendar_path: calendar.html
about_path: about.html
tags_path: tags.html

BASE_PATH:
